export const BASE_URL=process.env.REACT_APP_BACKEND;
export const COMMENTS_PER_POST=3
export const POST_PER_PAGE=2
export const CLOUDINARY_CLOUD_NAME=process.env.REACT_APP_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET=process.env.REACT_APP_CLOUD_UPLOAD_PRESETS;